### PR TITLE
Update module.js

### PR DESCRIPTION
**Pull request by zkochan**
@isaacs This seems to solve the issue I was describing [here](https://github.com/nodejs/node-eps/issues/46#issuecomment-266889663).

I hope my change makes sense. I can't spend a lot of time investigate it currently. I'll have more time on Saturday.

### CODE REVIEW

**Comment by isaacs** [comment]
That change undoes the core behavior change, resetting it back to the main behavior.

I think I see the bug here, though.  Can you back that out and try this diff instead?

```diff
diff --git a/lib/module.js b/lib/module.js
index c363e89..18a69e9 100644
--- a/lib/module.js
+++ b/lib/module.js
@@ -220,7 +220,7 @@ Module._findPath = function(request, paths) {
       if (!realpath) {
         return false;
       }
-      Module._pathCache[cacheKey] = filename;
+      Module._pathCache[cacheKey] = realpath;
       return filename;
     }
   }

```

**Comment by isaacs** [comment]
Oh, whoops, no.  That'll have the same effect, but it's not right.  Still investigating.

**Comment by isaacs** [comment]
It's very difficult for me to tell what tests are failing for what reason.  pnpm has a very big set of tests and many of the errors I'm seeing are unrelated to what you're describing.

Can you please provide a stripped down reproduction of just the situation you're seeing?

Maybe even just tar up the fixture directory with symlinks and whatnot, and tell me what file to try to run.

**Comment by isaacs** [comment]
Nevermind.  Fixed by 6d3c85f234fa058da62bf428ce39377291f5d56d.

**Comment by zkochan** [comment]
Thank you! Your fix indeed works.

**Pull request closed without merging**
